// ============================================================
// KotaKu Siaga — Administrative & Geographic Reference Data
// Study Area: Kota Semarang, Jawa Tengah, Indonesia
// Source: BPS Kota Semarang / Satu Data Kota Semarang (Public Open Data)
// Access: Tanpa Login / Tanpa API Key
// ============================================================

import type { AdministrativeArea } from './types'

export const STUDY_AREA_CONFIG = {
  name: 'Kota Semarang',
  code: '3374',
  province: 'Jawa Tengah',
  country: 'Indonesia',
  bbox: {
    minLat: -7.115,
    maxLat: -6.920,
    minLng: 110.270,
    maxLng: 110.500,
  },
  center: {
    lat: -6.9932,
    lng: 110.4203,
  },
}

export const SEMARANG_KECAMATAN: AdministrativeArea[] = [
  {
    id: '337401',
    slug: 'semarang-utara',
    name: 'Kecamatan Semarang Utara',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9554,
    center_lng: 110.4182,
    population: 128450,
    area_km2: 11.35,
    population_density: 11317,
    elevation_avg_m: 2.1,
    flood_vulnerability_index: 92, // Wilayah pesisir, penurunan tanah (land subsidence) aktif
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id/publication/kota-semarang-dalam-angka',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337402',
    slug: 'genuk',
    name: 'Kecamatan Genuk',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9542,
    center_lng: 110.4721,
    population: 118920,
    area_km2: 27.39,
    population_density: 4341,
    elevation_avg_m: 2.8,
    flood_vulnerability_index: 88, // Muara Kali Babon & Kali Tenggang, kawasan industri pantura
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337403',
    slug: 'gayamsari',
    name: 'Kecamatan Gayamsari',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9782,
    center_lng: 110.4521,
    population: 74210,
    area_km2: 6.18,
    population_density: 12008,
    elevation_avg_m: 3.5,
    flood_vulnerability_index: 78, // Koridor Kanal Banjir Timur & Tambak Dalam
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337404',
    slug: 'tembalang',
    name: 'Kecamatan Tembalang',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -7.0542,
    center_lng: 110.4501,
    population: 192800,
    area_km2: 44.20,
    population_density: 4362,
    elevation_avg_m: 180.0,
    flood_vulnerability_index: 68, // Kawasan perbukitan, limpasan permukaan deras & rawan gerusan
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337405',
    slug: 'pedurungan',
    name: 'Kecamatan Pedurungan',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -7.0012,
    center_lng: 110.4712,
    population: 198400,
    area_km2: 20.72,
    population_density: 9575,
    elevation_avg_m: 8.2,
    flood_vulnerability_index: 62, // Permukiman padat dataran tengah, genangan lokal
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337406',
    slug: 'ngaliyan',
    name: 'Kecamatan Ngaliyan',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9981,
    center_lng: 110.3341,
    population: 142100,
    area_km2: 37.99,
    population_density: 3740,
    elevation_avg_m: 75.0,
    flood_vulnerability_index: 55, // Zona perbukitan barat, limpasan Kali Silandak
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337407',
    slug: 'banyumanik',
    name: 'Kecamatan Banyumanik',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -7.0712,
    center_lng: 110.4121,
    population: 146300,
    area_km2: 25.69,
    population_density: 5694,
    elevation_avg_m: 210.0,
    flood_vulnerability_index: 45, // Dataran tinggi selatan, rawan longsor tebing curam
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337408',
    slug: 'semarang-barat',
    name: 'Kecamatan Semarang Barat',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9821,
    center_lng: 110.3842,
    population: 154300,
    area_km2: 21.74,
    population_density: 7097,
    elevation_avg_m: 6.5,
    flood_vulnerability_index: 72, // Muara Kali Banjir Kanal Barat & kawasan bandara
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337409',
    slug: 'semarang-timur',
    name: 'Kecamatan Semarang Timur',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9741,
    center_lng: 110.4381,
    population: 73500,
    area_km2: 7.70,
    population_density: 9545,
    elevation_avg_m: 4.0,
    flood_vulnerability_index: 76, // Saluran Kali Semarang lama & pemukiman padat
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337410',
    slug: 'semarang-tengah',
    name: 'Kecamatan Semarang Tengah',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9792,
    center_lng: 110.4191,
    population: 62400,
    area_km2: 6.14,
    population_density: 10162,
    elevation_avg_m: 5.0,
    flood_vulnerability_index: 66, // Pusat komersial & Kota Lama Semarang
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337411',
    slug: 'semarang-selatan',
    name: 'Kecamatan Semarang Selatan',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9962,
    center_lng: 110.4182,
    population: 70100,
    area_km2: 5.93,
    population_density: 11821,
    elevation_avg_m: 15.0,
    flood_vulnerability_index: 52, // Kawasan transisi Simpang Lima ke perbukitan
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337412',
    slug: 'candisari',
    name: 'Kecamatan Candisari',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -7.0142,
    center_lng: 110.4281,
    population: 78900,
    area_km2: 6.54,
    population_density: 12064,
    elevation_avg_m: 65.0,
    flood_vulnerability_index: 48, // Kawasan perbukitan tengah
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337413',
    slug: 'gajahmungkur',
    name: 'Kecamatan Gajahmungkur',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -7.0121,
    center_lng: 110.4042,
    population: 58200,
    area_km2: 9.07,
    population_density: 6416,
    elevation_avg_m: 85.0,
    flood_vulnerability_index: 44, // Perbukitan perumahan elite & lereng terjal
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337414',
    slug: 'tugu',
    name: 'Kecamatan Tugu',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -6.9682,
    center_lng: 110.3121,
    population: 34800,
    area_km2: 31.78,
    population_density: 1095,
    elevation_avg_m: 3.0,
    flood_vulnerability_index: 82, // Pesisir barat, tambak & muara Kali Beringin
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337415',
    slug: 'mijen',
    name: 'Kecamatan Mijen',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -7.0541,
    center_lng: 110.3142,
    population: 82300,
    area_km2: 57.55,
    population_density: 1430,
    elevation_avg_m: 140.0,
    flood_vulnerability_index: 38, // Dataran tinggi perkebunan & hulu sungai
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
  {
    id: '337416',
    slug: 'gunungpati',
    name: 'Kecamatan Gunungpati',
    city: 'Kota Semarang',
    province: 'Jawa Tengah',
    center_lat: -7.0892,
    center_lng: 110.3721,
    population: 96400,
    area_km2: 54.11,
    population_density: 1781,
    elevation_avg_m: 260.0,
    flood_vulnerability_index: 35, // Kawasan konservasi hijau & kampus UNNES
    provenance: {
      provider: 'BPS_Semarang',
      source_type: 'official_open_data',
      source_reference: 'https://semarangkota.bps.go.id',
      retrieved_at: new Date().toISOString(),
      license: 'Public Domain / Open Government Data',
      access_method: 'PUBLIC_NO_AUTH',
    },
  },
]
